import type { Metadata } from "next"
import "./globals.css"
import { ProseProvider } from "@/app/prose-context"
import { LayoutContent } from "@/components/LayoutContent"

// Removed Google font imports to avoid fetch error during build. You can add local fonts if needed.

export const metadata: Metadata = {
  title: "国学力量",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className="antialiased"
      >
        <ProseProvider>
          <LayoutContent>
            {children}
          </LayoutContent>
        </ProseProvider>
      </body>
    </html>
  )
}
